"""Add delivery task/Change index

Revision ID: 3ee8129175d8
Revises: 91c2ff7519d4
Create Date: 2025-11-11 13:32:51.958555

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3ee8129175d8"
down_revision: Union[str, Sequence[str], None] = "91c2ff7519d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "delivery_tasks",
        sa.Column("outbox_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["outbox_id"],
            ["outbox.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["engine_subscriptions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "outbox_id", "subscription_id", name="uq_bot_delivery_task"
        ),
    )
    op.create_index(
        "ix_delivery_task_pending",
        "delivery_tasks",
        ["next_attempt_at"],
        unique=False,
        postgresql_where=sa.text("published IS false"),
    )
    op.drop_index(
        op.f("ix_bot_delivery_task_pending"),
        table_name="bot_delivery_tasks",
        postgresql_where="(published IS FALSE)",
    )
    op.drop_table("bot_delivery_tasks")
    op.add_column(
        "engine_subscriptions", sa.Column("event", sa.String(), nullable=False)
    )
    op.drop_constraint(
        op.f("engines_version_timestamp_version_seq_key"), "engines", type_="unique"
    )
    op.create_unique_constraint(
        "uq_engine_version", "engines", ["version_timestamp", "version_seq"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_engine_version", "engines", type_="unique")
    op.create_unique_constraint(
        op.f("engines_version_timestamp_version_seq_key"),
        "engines",
        ["version_timestamp", "version_seq"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("engine_subscriptions", "event")
    op.create_table(
        "bot_delivery_tasks",
        sa.Column("outbox_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("subscription_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("message", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("published", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "published_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "next_attempt_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["outbox_id"], ["outbox.id"], name=op.f("bot_delivery_tasks_outbox_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["engine_subscriptions.id"],
            name=op.f("bot_delivery_tasks_subscription_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("bot_delivery_tasks_pkey")),
    )
    op.create_index(
        op.f("ix_bot_delivery_task_pending"),
        "bot_delivery_tasks",
        ["next_attempt_at"],
        unique=False,
        postgresql_where="(published IS FALSE)",
    )
    op.drop_index(
        "ix_delivery_task_pending",
        table_name="delivery_tasks",
        postgresql_where=sa.text("published IS false"),
    )
    op.drop_table("delivery_tasks")
    # ### end Alembic commands ###
