environment: dev
container:
  tag: dev
securityContext:
  runAsNonRoot: false
  runAsUser: 0

config:
  POSTGRES__DB_NAME: netku_debug
  REDIS__DB: "0"
  REDIS__PORT: "6382"
  RABBIT_PROXY_VHOST: "/test/proxy"
  RABBIT__USERNAME: "test"

# --- API ---
api:
  replicas: 1
  ingress:
    host: dev.proxy.infanasotku.com
  container:
    args:
      [
        "app.entrypoints.api:app",
        "--proxy-headers",
        "--forwarded-allow-ips=*",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5100",
        "--reload"
      ]

events:
  replicas: 1
  container:
    args:
      [
      "app.entrypoints.events:app",
      "--workers",
      "1",
      "--host",
      "0.0.0.0",
      "--port",
      "5101",
      "--reload"
    ]

outbox:
  replicas: 1
  container:
    args:
      [
      "app.entrypoints.outbox_relay:app",
      "--workers",
      "1",
      "--host",
      "0.0.0.0",
      "--port",
      "5102",
      "--reload"
    ]
