# --- COMMON ---
container:
  image: registry.infanasotku.com:5501/netku/netku-proxy
  tag: latest
environment: prod
name: netku-proxy
securityContext:
  runAsNonRoot: true
  runAsUser: 1000

config:
  POSTGRES__DB_NAME: netku
  REDIS__DB: "0"
  REDIS__PORT: "6381"
  RABBIT_PROXY_VHOST: "/proxy"
  RABBIT__USERNAME: "proxy"

# --- API ---
api:
  version: "0.1.8"
  replicas: 2
  container:
    name: netku-proxy-api
    port: 5100
    args:
      [
        "app.entrypoints.api:app",
        "--proxy-headers",
        "--forwarded-allow-ips=*",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5100",
      ]
  ingress:
    host: proxy.infanasotku.com
    path: /

# --- EVENTS ---
events:
  version: "0.1.9"
  replicas: 2
  container:
    name: netku-proxy-events
    port: 5101
    args:
      [
        "app.entrypoints.events:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5101",
      ]

# --- OUTBOX ---
outbox:
  version: "0.1.9"
  replicas: 2
  container:
    name: netku-proxy-outbox
    port: 5102
    args:
      [
        "app.entrypoints.outbox:app",
        "--workers",
        "1",
        "--host",
        "0.0.0.0",
        "--port",
        "5102",
      ]
