environment: prod
container:
  tag: latest

config:
  POSTGRES__DB_NAME: netku
  REDIS__DB: "0"
  REDIS__PORT: "6381"
  RABBIT_PROXY_VHOST: "/proxy"
  RABBIT__USERNAME: "proxy"

# --- API ---
api:
  ingress:
    host: proxy.infanasotku.com
