apiVersion: v1
kind: ConfigMap
metadata:
  name: netku-proxy-config
data:
  # Admin
  ADMIN__USERNAME: "admin"

  # Postgres
  POSTGRES__USERNAME: infanaserver
  POSTGRES__DB_NAME: {{ .Values.config.POSTGRES__DB_NAME }}
  POSTGRES__HOST: local.infanasotku.com.
  POSTGRES__PORT: "5430"
  POSTGRES__SQL_SCHEMA: proxy

  # RabbitMQ
  RABBIT__USERNAME: proxy
  RABBIT__HOST: rabbitmq.infanasotku.com.
  RABBIT__PORT: "5670"
  RABBIT_SCOPE_VHOST: /client
  RABBIT_PROXY_VHOST: /proxy

  # Redis
  REDIS__HOST: redis.infanasotku.com.
  REDIS__PORT: "6381"
  REDIS__DB: {{ .Values.config.REDIS__DB }}
