apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.outbox.container.name }}-{{ .Values.environment }}
  annotations:
    infanasotku.com: "Infanasotku software engineer"

spec:
  replicas: {{ .Values.outbox.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.outbox.container.name }}

  template:
    metadata:
      labels:
        app: {{ .Values.outbox.container.name }}
        environment: {{ .Values.environment }}
        version: {{ .Values.outbox.version }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}

    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}

      containers:
        - name: {{ .Values.outbox.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: Always

          command: ["uvicorn"]
          args: {{ .Values.outbox.container.args | toJson }}
          ports:
            - containerPort: {{ .Values.outbox.container.port }}

          envFrom:
            - configMapRef:
                name: netku-proxy-config
            - secretRef:
                name: netku-proxy-secrets

          {{- if ne .Values.environment "dev" }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{.Values.outbox.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: {{.Values.outbox.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- end }}

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          securityContext:
            capabilities:
              drop: ["ALL"]

      imagePullSecrets:
        - name: regcred
