apiVersion: v1
kind: Secret
metadata:
  name: netku-proxy-secrets
type: Opaque
stringData:
{{- $secrets := .Files.Get "temp-secrets.yaml" | fromYaml }}
{{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
