name: CD
on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  load-pr:
    name: Load PR data
    uses: ./.github/workflows/load-pr-data.yml

  build-or-retag:
    name: Prepare :latest image
    runs-on: ubuntu-latest
    environment: staging-deploy
    needs: load-pr
    if: |
      contains(fromJson(needs.load-pr.outputs.pr_data).labels.*.name, 'events') ||
      contains(fromJson(needs.load-pr.outputs.pr_data).labels.*.name, 'api')

    steps:
      - uses: actions/checkout@v4

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - id: check-image
        name: Check if SHA image exists (from staging)
        shell: bash
        run: |
          if docker manifest inspect "${{ vars.REGISTRY_URL }}/netku/netku-proxy:${{ github.sha }}" >/dev/null 2>&1; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Retag and push :latest from :${{ github.sha }}
        if: steps.check-image.outputs.exists == 'true'
        run: |
          docker pull "${{ vars.REGISTRY_URL }}/netku/netku-proxy:${{ github.sha }}"
          docker tag  "${{ vars.REGISTRY_URL }}/netku/netku-proxy:${{ github.sha }}" "${{ vars.REGISTRY_URL }}/netku/netku-proxy:latest"
          docker push "${{ vars.REGISTRY_URL }}/netku/netku-proxy:latest"

      - name: Build and push :latest (staging image not found)
        if: steps.check-image.outputs.exists == 'false'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ vars.REGISTRY_URL }}/netku/netku-proxy:latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build-or-retag, load-pr]
    environment: staging-deploy

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
      - name: Build Helm flags from PR labels
        id: helm_flags
        env:
          SERVICES_KEYS: ${{ vars.SERVICES_KEYS }}
          PR_DATA: ${{ needs.load-pr.outputs.pr_data }}
        shell: bash
        run: |
          set -euo pipefail
          FLAGS=""

          LABELS=""
          if [ -n "${PR_DATA:-}" ]; then
            LABELS="$(echo "$PR_DATA" | jq -r '.labels[].name' 2>/dev/null | tr '\n' ' ' || true)"
          fi

          IFS=',' read -ra SRV <<< "${SERVICES_KEYS}"
          for svc in "${SRV[@]}"; do
            key="$(echo "$svc" | xargs)"
            [ -z "$key" ] && continue
            if echo " $LABELS " | grep -q " $key "; then
              FLAGS="$FLAGS --set $key.enabled=true"
            else
              FLAGS="$FLAGS --set $key.enabled=false"
            fi
          done

          echo "flags=$FLAGS" >> "$GITHUB_OUTPUT"
      - name: Deploy via SSH
        run: |
          ssh -p ${{ secrets.SSH_PORT }} root@${{ secrets.SERVER_IP }} << 'EOF'
            cd ${{ secrets.PROJECT_DIR }}

            sops -d k8s/encoded-secrets.yaml > k8s/temp-secrets.yaml && \
            helm upgrade --install netku-proxy-prod -f k8s/values-prod.yaml \
            ${{ steps.helm_flags.outputs.flags }} --set container.tag=latest --namespace netku-prod k8s \
            && rm k8s/temp-secrets.yaml
          EOF
